#!/bin/bash
echo "=== 设置 Vercel 环境变量 ==="
echo ""
echo "请按顺序运行以下命令，并输入对应的值："
echo ""
echo "1. 添加 OpenRouter API Key:"
echo "vercel env add OPENROUTER_API_KEY production"
echo ""
echo "2. 添加 OpenRouter API URL (可选，直接回车使用默认值):"
echo "vercel env add OPENROUTER_API_URL production"
echo ""
echo "3. 添加 万相 API Key:"
echo "vercel env add WANXIANG_API_KEY production"
echo ""
echo "4. 添加应用的公开 URL (可选):"
echo "vercel env add NEXT_PUBLIC_APP_URL production"
echo ""
echo "设置完成后，运行以下命令重新部署："
echo "vercel --prod"